import { rgba } from "polished";

const theme = {
//   gutterWidth: "0.5rem",
//   containerMaxWidthXs: "100%",
//   containerMaxWidthSm: "100%",
//   containerMaxWidthMd: "100%",
//   containerMaxWidthLg: "1080px",
//   containerMaxWidthXl: "1200px",
//   screenWidthXs: "576px",
//   screenWidthSm: "768px",
//   screenWidthMd: "992px",
//   screenWidthLg: "1200px",
//   screenWidthXl: "1920px",
//   sidebarWidth: "56px",
//   sidebarWidthMd: "220px",
//   colorForDark1: rgba("white", 0.96),
//   colorForDark2: rgba("white", 0.65),
//   colorForDark3: rgba("white", 0.45),
  fontFamily: "Poppins",
  fontWeightBold: 600,
  fontWeightSemibold: 500,
  fontWeightRegular: 400,
//   heightCardMd: "360px",
//   heightChartMd: "150px",
  lenSm1: "0.25rem",
  lenSm2: "0.5rem",
  lenSm3: "0.75rem",
//   lenMd1: "10rem",
  marginTop: "10rem",
  marginBottom: "10rem",
  marginRight: "40rem",
  marginLeft: "40rem",
//   lenMd2: "5rem",
  cardTitleFontSize: "3rem",
//   lenMd3: "100rem",
  paddingBottomCard: "0rem",
  paddingTopCard: "0rem",
  paddingRightCard: "0rem",
  paddingLeftCard: "0rem",
  lenLg1: "2rem",
  lenLg2: "3rem",
  lenLg3: "4rem",
  lenXl1: "5rem",
//   lenXl2: "6rem",
  cardTitleHeight: "8rem",
  lenXl3: "7rem",
};

export default theme;